spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:15432/postgres?currentSchema=public
#    url: jdbc:postgresql://localhost:15432/postgres?currentSchema=public
    username: postgres
    password: postgres